//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 11:38:49 AM CEST 
//

package pl.com.tt.projectmanagementsystem.xmlUtil;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "user" })
@XmlRootElement(name = "Users")
public class Users {

	@XmlElement(name = "User", required = true)
	protected List<Users.User> user;

	public List<Users.User> getUser() {
		if (user == null) {
			user = new ArrayList<Users.User>();
		}
		return this.user;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "permissions" })
	public static class User {

		@XmlElement(required = true)
		protected List<String> permissions;
		@XmlAttribute(name = "name")
		protected String name;

		public List<String> getPermissions() {
			return permissions;
		}

		public void setPermissions(List<String> value) {
			this.permissions = value;
		}

		public String getName() {
			return name;
		}

		public void setName(String value) {
			this.name = value;
		}

	}

}
